#!/usr/bin/perl -wT

# save the entered info to a file & redisplay
# this script is intended to management info that is editable by 
# the course intructors:  course.cgi is a more general tool

$ENV{PATH} = "/bin:/usr/bin";

use lib "/www/Gform/lib/";
use lib "/www/Gform/SMS/lib/";

use Debug;
use SMS_Person;
use signupform;
use SMS_html_Util;

use HTML_Util;
use Form_Util;

use strict;
use CGI;
use Date::Calc qw [Today Add_Delta_Days Delta_Days Day_of_Week Monday_of_Week Week_of_Year];
use CGI::Carp 'fatalsToBrowser';
my $today     = sprintf ("%04d-%02d-%02d", Today() );

my $this_script = "/cgi-bin/SMS2/Edit";
my $title = "P &amp; A Student Shop Sign Up";
my $version = "0.0.1";
Debug::Set_Debug(1, "html");
my ($wel, $fname);
my $sp = '&nbsp;';
my $q = new CGI;
my $Debug = 2;



print $q->header(-type=> "text/html", -expires=>'now'), "\n";
print $q->start_html( -title  =>  $title, 
                      -style  => [ {'src'=>'/Status/lib/note.css', },
                                   {'src'=>'/Gform/SMS/css/reset.css'}, 
                                   {'src'=>'/Gform/SMS/css/zebra_datepicker.css'},
                                   {'src'=>'/Gform/SMS/css/style.css'}, 
                                   {'src'=>'/Gform/SMS/css/SMS.css'},
                                   {'src'=>'/Gform/SMS/css/shCoreDefault.css'}
                                 ],
                       -script => [ {-type=>"text/javascript",
                                     -src=>"/Gform/SMS/javascript/jquery-1.8.2.js"},
                                    {-type=>"text/javascript",
                                      -src=>"/Gform/SMS/javascript/XRegExp.js"},
                                    {-type=>"text/javascript",
                                      -src=>"/Gform/SMS/javascript/shCore.js"},
                                    {-type=>"text/javascript",
                                      -src=>"/Gform/SMS/javascript/shBrushJScript.js"},
                                    {-type=>"text/javascript",
                                      -src=>"/Gform/SMS/javascript/myzebradp1.js"},
                                    ]
                      ),"\n";
print signupform::mk_myfuncs();
Debug::dsay("this is Edit...");

dump_it();
print $q->start_multipart_form("POST", $this_script), "\n";

my ($this_y, $this_m, $this_d) = Today();
my @exp_date = Add_Delta_Days ($this_y, $this_m, $this_d, 30);

my $now =  sprintf("%4d-%2.2d-%2.2d",$this_y,$this_m,$this_d);  
my $then = sprintf("%4d-%2.2d-%2.2d",$exp_date[0], $exp_date[1],$exp_date[2]);

print $q->start_multipart_form("POST", $this_script), "\n";


if ($q->param('Submit_Reg') )  { do_check_params();}
else                           { do_mainpage2(); }

print $q->endform;
print $q->end_html;
exit;

sub do_mainpage2 {

   Debug::dsay ("This is main page2 sub ;");

	my $cn = $q->param("confirmationnumber");
    my $sn = SMS_Person::cn2sn($cn);
	print  qq{<div class="mainpg>"};

#	print "<h2> Dump of the query </h2><br />\n";
#    print $q->Dump;
#    print "<hr />";

    print SMS_Person::get_hdr();
    print  get_Intro();

	my $html = SMS_html_Util::edit_student_register($q, "student", $sn);

	print $html;
	print $q->hidden ( -name=>"confirmationnumber", -default=>[$cn]); 
    print  qq{</div>};
}

sub do_check_params{
    Debug::dsay ("do_check_params:: ");
	my $err = SMS_html_Util::check_input($q);

	if ($err) {
		print $err;
		my $sn = $q->param("UBC_id");
		my $html = SMS_html_Util::edit_student_register($q, "student", $sn);
		my $qsub =$q->submit( -name  => "Submit_Reg",
                        
                       -value => "Submit"); 
		$html .=   qq{<p>$qsub</p>};
		print $html;
	} else {
		do_Save();
	}
}
sub do_Save {
    my %element_info =  SMS_Person::get_element_info();
    my $id = $q->param("ID") ? $q->param("ID") : "";
    my $part  = SMS_Person::new();
    Debug::dsay ("do_Save new version -- copying cgi params in hash;id {$id}");
    my $summ = "<table>";
	my $asum = "\n";
	foreach my $ftag ( $q->param ) {
		next if ($ftag =~ /Submit/ );
		if ($ftag =~ /_[AP]M$/) {
			my $tag  =  $ftag;
			my $value = "Yes";
			$part->{$tag}  = $value;
			$summ .= qq{<tr><td class="thanks">$tag: </td><td>$value</td></tr>};
			$asum .= sprintf "%-20s : %s\n",$tag, $value;
		}
		else {
			$part->{$ftag}  = $q->param($ftag);
			my $value = $part->{$ftag};
			$summ .= qq{<tr><td class="thanks">$ftag: </td><td>$value</td></tr>} if $value;
			$asum .= sprintf ("%-20s : %s\n",$ftag, $value) if $value;;
		}
	}

 
    my $err = SMS_Person::save( $part, $id);
    do_thanks($summ, );
}

sub do_thanks
{
#   my $name = $q->param{"full_name"};
    my $summ = shift;

    my $out = qq{ <div class="thanks"><h1 class="SMS">SMS signup</h1>
                <p> Thank you  for your continued interest in the student shop course. <br /> 
               The following  information has been recorded </p> $summ <br /> </div> };
    print $out;
    
}


sub get_Intro
{
    my $app =shift;
    my $name = $app->{full_name};
    my $ifile = "/www/Gform/SMS_Person/lib/edit_intro_text";

    my $intro = "";
    {
	open (X, $ifile) || warn "cannot open $ifile \n";
	local ( $/ );
	$intro = <X>;
	close X;  
    }
    $intro =~ s/%%App%%/$name/;
    return $intro;
}

sub dump_it
{
	print "<h2> Dump of the query </h2><br />\n";
        print $q->Dump;
        print "<hr />";
}


