#!/usr/bin/perl -wT

# save the entered info to a file & redisplay
# this script is intended to management info that is editable by 
# the course intructors:  course.cgi is a more general tool

$ENV{PATH} = "/bin:/usr/bin";

use lib "/www/Gform/lib/";
use lib "/www/Gform/SMS/lib";

use Debug;
use SMS_Person;
use course_metadata;
use signupform;

use HTML_Util;
use Form_Util;
use SMS_html_Util;

use strict;
use CGI;
use Date::Calc qw [Today Add_Delta_Days Delta_Days Day_of_Week Monday_of_Week Week_of_Year];
use CGI::Carp 'fatalsToBrowser';
my $today     = sprintf ("%04d-%02d-%02d", Today() );

my $this_script = "/cgi-bin/SMS2/Signup";
my $title = "P &amp; A Student Shop Sign Up";
my $version = "0.0.1";
Debug::Set_Debug(1, "html");
my ($wel, $fname);
my $sp = '&nbsp;';
my $q = new CGI;
#my $Debug = 2;
my $bs_style = "buttonstyle";
my $qsave =$q->submit( -name  => "Save",
                       -class => $bs_style,      
                       -value => "Save"); 
my $Hidden;

print $q->header(-type=> "text/html", -expires=>'now'), "\n";
print $q->start_html( -title  =>  $title, 
                      -style  => [ {'src'=>'/Status/lib/note.css', },
                                   {'src'=>'/Gform//sshop/css/reset.css'}, 
                                   {'src'=>'/Gform//sshop/css/zebra_datepicker.css'},
                                   {'src'=>'/Gform//sshop/css/style.css'}, 
                                   {'src'=>'/Gform//SMS/css/sshop.css'},
                                   {'src'=>'/Gform/sshop/css/shCoreDefault.css'}
                                 ],
                       -script => [ {-type=>"text/javascript",
                                     -src=>"/Gform/sshop/javascript/jquery-1.8.2.js"},
                                    {-type=>"text/javascript",
                                      -src=>"/Gform/sshop/javascript/XRegExp.js"},
                                    {-type=>"text/javascript",
                                      -src=>"/Gform/sshop/javascript/shCore.js"},
                                    {-type=>"text/javascript",
                                      -src=>"/Gform/sshop/javascript/shBrushJScript.js"},
                                    {-type=>"text/javascript",
                                      -src=>"/Gform/sshop/javascript/myzebradp1.js"},
                                    ]
                      ),"\n";
print signupform::mk_myfuncs();

dump_it();
print $q->start_multipart_form("POST", $this_script), "\n";

my ($this_y, $this_m, $this_d) = Today();
my $isotoday = sprintf "%4d%2.2d%2.2d", Today();
my @exp_date  = Add_Delta_Days ($this_y, $this_m, $this_d, 30);

my $now =  sprintf("%4d-%2.2d-%2.2d",$this_y,$this_m,$this_d);  
my $then = sprintf("%4d-%2.2d-%2.2d",$exp_date[0], $exp_date[1],$exp_date[2]);

print $q->start_multipart_form("POST", $this_script), "\n";

if ($q->param('Save') )  { do_Save();}
else                     { do_mainpage2(); }

print $q->endform;
print $q->end_html;
exit;

sub do_mainpage2 {

   Debug::dsay ("This is main page2 sub ;");
	print  qq{<div class="mainpg"};
    print  get_Intro();

	my $html = SMS_html_Util::student_register($q, "student");

	print $html;
    print  qq{<p>$qsave</p>};
    print  qq{</div>};
}
sub do_mainpage {
    Debug::dsay ("This is main page sub ;");
    my %element_info = SMS_Person::get_element_info();


    print qq{<div class="mainpg"};
    print get_Intro();
    print qq{<table border="1" cellpadding="4" cellspacing="10" width="600px">\n};   
    foreach my $t ( sort {$element_info{$a}{rank} <=>
                          $element_info{$b}{rank} }
                   keys %element_info ) {
   ###  Debug::dsay("do_form:: t is {$t}");

#		next if $t =~ /omment/;
		next if ( $element_info{$t}{cat} eq "admin"  );
		print "<p> tag {$t} is typed {$element_info{$t}{qtype}}</p>" 
          if ($element_info{$t}{qtype} eq "AoH");
		my $value = $q->param($t) ? $q->param($t) : "" ;
		my $pout = $element_info{$t}{prompt} ? $element_info{$t}{prompt}: "";
		my $qout = $element_info{$t}{qtype}  ? $element_info{$t}{qtype} : "";
		next unless $pout;
		$pout =~ s[\s+][\&nbsp;]g;
     
		print qq{<tr> <td class="prompt"> $pout: </td>\n}; 
    
		$value = $today  if ($t eq "date" and !$value);                
		my $out = Form_Util::input_query(\%{$element_info{$t}}, $t, $value);

		my $req = defined ($t->{required})
             ? qq{<span id="req"> &#9756;</span>}
			 : q[&nbsp;];

		print qq{<td class="input"> $out</td> <td>$req</td>};
		print qq{</tr>\n};
	}
	print qq{ <tr><td class="explain" colspan="2"> Below is the list of upcoming courses.
 
    You can check the
	<a href="JavaScript:newPopup('http://gamma.phas.ubc.ca/cgi-bin/SMS2/mkcal');">SMS Calendar</a> for available dates.
              </td></tr>};
    my $n_mods = 9;
    

	my $data = course_metadata::get_Course_Data_json();
	my @courses = @{$data->{course_data}};
	my $ctable = "";
	my $headers = qq{<tr>};
	$headers   .= qq{<th class="ct">Modules</th>};
	$headers   .= qq{<th class="ct">Title</th>};
	$headers   .= qq{<th class="ct">Date</th>};
	$headers   .= qq{<th class="ct">Request</th>};
	$headers   .= qq{<th class="ct">Registered</th>};
	$headers   .= qq{<th class="ct">Completed</th>};
	$headers   .= qq{</tr>};
	my $modnum;
	foreach my $c (  @courses ) {
		$modnum = $c->{num};
		my $title  = $c->{title};
		$ctable .= qq{  <tr><td class="ct"> Module # $modnum</td>};
		$ctable .= qq{      <td  class="ct"> $title</td>};
		my @dates = @{$c->{date_upcoming}};
		my $dtable = "";
		$ctable .= qq{  <td  class="ct">};
		foreach my $date ( @dates ) {
			next if $date < $isotoday;
			$ctable .= qq{  $date<br />};
		}
		$ctable .= qq{</td> <td  class="ct"> };
		foreach my $date ( @dates ) {
			next if $date < $isotoday;
			my $but = "$modnum.ask.$date";
			my $xbut = $q->checkbox(-name=>$but,
			                        -checked=>0,
									-value=>'ON',
									-label=>' ');
			$ctable .= qq{  $xbut<br />};
		}
		$ctable .= qq{</td> <td  class="ct"> };
		foreach my $date ( @dates ) {
			next if $date < $isotoday;
			
			$ctable .= qq{     --<br />};
		}
		$ctable .= qq{</td> <td  class="ct"> };
		foreach my $date ( @dates ) {
			next if $date < $isotoday;
			
			$ctable .= qq{  --<br />};
		}
		$ctable .= qq{</td> };
	#	$ctable .= qq{<td><table class="dtable">$dtable</table></tr>};
		$ctable .= qq{</tr>\n};
    }
	print qq{<table id="ctable">$headers $ctable</table>};     
 
###write the Comments...
    # my $t = "comment";
    # my $value = $q->param($t) ? $q->param($t) : "" ;
    # my $pout = $element_info{$t}{prompt} ? $element_info{$t}{prompt}: "";
    # my $qout = $element_info{$t}{qtype}  ? $element_info{$t}{qtype} : "";
    # print qq{<tr> <td class="prompt"> $pout: </td>\n};                   
    # my $out = Form_Util::input_query(\%{$element_info{$t}}, $t, $value);
    # print qq{<td class="input"> $out</td></tr>\n};  
    #print "</table>\n";
    print "<p>$qsave</p>";
    print qq{</div>};
}

sub do_Save {
    my %element_info =  SMS_Person::get_element_info();
   
    my $part  = SMS_Person::new();
    my $summ = "<table>";
    my $app_info = "";
    Debug::dsay ("Admin::do_Save new version -- copying cgi params in hash;");

	foreach my $ftag ( $q->param ) {
		next if ($ftag eq "Save");
		if ($ftag =~ /_[AP]M$/) {
			
			my $tag  = "avail_" . $ftag;
			my $value = $q->param($ftag);
			$part->{$tag}  = $value;
			$summ .= qq{<tr><td class="thanks">$tag: </td><td>$value</td></tr>};
		}
		else {
			$part->{$ftag}  = $q->param($ftag);
			my $pp = $part->{$ftag};
			$summ .= qq{<tr><td class="thanks">$ftag: </td><td>$pp</td></tr>} if $pp;
		}
	}
	my $id = $part->{UBC_id};
	my $cn = SMS_Person::confirmationnumber($id);
	$part->{conf_num} = $cn;
#    foreach my $t ( sort {$element_info{$a}{rank} <=>
#                          $element_info{$b}{rank} }
#					keys %element_info ) {
#        next if ($t eq "ID");
#        $part->{$t}  = $q->param($t) ?  $q->param($t) : "";
#		if ($t =~/^\d/ ) {
#			Debug::dsay ( "Admin::do_Save:: tag is now {$t}");
#
#		}
#
#        my $pp = $part->{$t};
#        $summ .= qq{<tr><td class="thanks">$t: </td><td>$pp</td></tr>} if $pp;
#        $app_info .= "$t:  $pp\n" if $pp;
#    }
    my $today = sprintf "%4d%2.2d%2.2d", Today();
    $part->{"date_request"} = $today;

	foreach my $tt ( keys %element_info) {
		my $val = $part->{$tt};
		Debug::dsay( " tag [$tt] value [$val]"); 
	}
    my $xid = SMS_Person::save( $part );
    Debug::dsay ("do_Save:: id is {$xid}");
   
 
    $summ .= qq{</table>};
    do_thanks($summ, $cn);
    # try mailing this info to course admin
    SMS_Person::mail_signup($app_info);
}

sub do_thanks {
#   my $name = $q->param{"full_name"};
    my $summ = shift;
    my $cn = shift;
    my $out = qq{ <div class="thanks"><h1 class="SMS">SMS signup</h1>
                <p> Thanks for your interest in the student shop course. <br /> 
               The following  information has been recorded </p> $summ <br /> <p>You should receive
               an invitation to a course via email when you are 
               scheduled <br /> To change your info, go to 
             <a href="http://sms.phas.ubc.ca/cgi-bin/SMS/Edit?cn=$cn">
                http://sms.phas.ubc.ca/cgi-bin/SMS/Edit?cn=$cn</a>
              </p></div> };
    print $out;
}

sub get_Intro {
    my $ifile = "/www/Gform/sshop/lib/signup_intro_text";

    my $intro = "";
    {
	open (X, $ifile) || warn "cannot open $ifile \n";
	local ( $/ );
	$intro = <X>;
	close X;  
    }
   return $intro;
}

sub dump_it
{
	print "<h2> Dump of the query </h2><br />\n";
        print $q->Dump;
        print "<hr />";
}


