#!/usr/bin/perl -w

# save the entered info to a file & redisplay
# this script is intended to management info that is editable by 
# the course intructors:  course.cgi is a more general tool

$ENV{PATH} = "/bin:/usr/bin";

use lib "/www/Gform/lib/";
use lib "../lib";

use Debug;
use SMS_Person;
use course_metadata;
use HTML_Util;
use Form_Util;
use SMS_html_Util;

use strict;
use CGI;
use Date::Calc qw [Today Add_Delta_Days Delta_Days Day_of_Week Monday_of_Week Week_of_Year];
use CGI::Carp 'fatalsToBrowser';
my $today     = sprintf ("%04d-%02d-%02d", Today() );

my $this_script = "/cgi-bin/SMS2/cgi/xSignup";
my $title = "P &amp; A Student Shop Sign Up";
my $version = "0.0.1";
my $webhost = SMS_Person::webhost();

Debug::Set_Debug(1, "html");
my ($wel, $fname);
my $sp = '&nbsp;';
my $q = new CGI;

my $bs_style = "buttonstyle";

my $Hidden;

print $q->header(-type=> "text/html", -expires=>'now'), "\n";
print $q->start_html( -title  =>  $title, 
                      -style  => [ 
                                   {'src'=>'/css/SMS.css'},
        
                                 ],
#                       -script => [ {-type=>"text/javascript",
#                                     -src=>"/Gform/sshop/javascript/jquery-1.8.2.js"},
#                                    {-type=>"text/javascript",
#                                      -src=>"/Gform/sshop/javascript/XRegExp.js"},
#                                    {-type=>"text/javascript",
#                                      -src=>"/Gform/sshop/javascript/shCore.js"},
#                                    {-type=>"text/javascript",
#                                      -src=>"/Gform/sshop/javascript/shBrushJScript.js"},
#                                    {-type=>"text/javascript",
#                                      -src=>"/Gform/sshop/javascript/myzebradp1.js"},
#									{ -type=>"text/javascript",
#                                      -src=>"/Gform/SMS/js/validates.js"},
#                                    ]
                      ),"\n";

dump_it();

my $qsave =$q->submit( -name  => "Save",
                       -class => $bs_style,      
                       -value => "Save");
my $qsub =$q->submit( -name  => "Submit_Reg",
                       -class => $bs_style,      
                       -value => "Submit"); 
print $q->start_multipart_form("POST", $this_script), "\n";

my ($this_y, $this_m, $this_d) = Today();
my $isotoday = sprintf "%4d%2.2d%2.2d", Today();
my @exp_date  = Add_Delta_Days ($this_y, $this_m, $this_d, 30);

my $now =  sprintf("%4d-%2.2d-%2.2d",$this_y,$this_m,$this_d);  
my $then = sprintf("%4d-%2.2d-%2.2d",$exp_date[0], $exp_date[1],$exp_date[2]);

print $q->start_multipart_form("POST", $this_script), "\n";

if    ($q->param('Submit_Reg') )    { do_check_params();}
elsif ($q->param('Save') )          { do_Save();}
else                     	        { do_mainpage2(); }

print $q->endform;
print $q->end_html;
exit;

sub do_mainpage2 {

#   Debug::dsay ("This is main page2 sub ;");

	print  qq{<div class="mainpg>"};
    print  get_Intro();

	my $html = SMS_html_Util::student_register($q, "student");

	print $html;
    print  qq{</div>};
}


sub do_Save {
    my %element_info =  SMS_Person::get_element_info();
    Debug::dsay ("Signup::do_Save ;");
    my $part  = SMS_Person::new();
    my $summ = "<table>";

	my $asum = qq { Thanks for your interest in the student shop courses. \n
The following information has been recorded\n\n};
	my $tab = " "x4;
    my $app_info = "";
    Debug::dsay ("Admin::do_Save new version -- copying cgi params in hash;");

	foreach my $ftag ( $q->param ) {
		next if ($ftag =~ /Submit/ );
		if ($ftag =~ /_[AP]M$/) {
			my $tag  =  $ftag;
			my $value = "Yes";
			$part->{$tag}  = $value;
			$summ .= qq{<tr><td class="thanks">$tag: </td><td>$value</td></tr>};
			$asum .= sprintf "%-20s : %s\n",$tag, $value;
		}
		else {
			$part->{$ftag}  = $q->param($ftag);
			my $value = $part->{$ftag};
			$summ .= qq{<tr><td class="thanks">$ftag: </td><td>$value</td></tr>} if $value;
			$asum .= sprintf ("%-20s : %s\n",$ftag, $value) if $value;;
		}
	}
	my $id = $part->{UBC_id};
	my $cn = SMS_Person::confirmationnumber($id);
	$part->{confirmationnumber} = $cn;
    Debug::dsay ("Admin::do_Save:;cn is [$cn");
#	$summ .= qq{<tr><td class="thanks">confirmationnumber: </td><td>$cn</td></tr>};
#	$asum .= sprintf "%-20s : %s\n","confirmationnumber", $cn;

    my $today = sprintf "%4d%2.2d%2.2d", Today();
    $part->{"date_signup"} = $today;
	$summ .= qq{<tr><td class="thanks">confirmationnumber: </td><td>$cn</td></tr>};
	$asum .= sprintf "%-20s : %s\n","confirmationnumber", $cn;

    my $xid = SMS_Person::save( $part );
   
    $summ .= qq{</table>};
    do_thanks($summ, $cn);
    # try mailing this info to course admin
	Debug::dsay ("SignUp:: do_Save:: webhost [$webhost]  ");
 #   SMS_Person::mail_signup($app_info);
	Debug::dsay ("SignUp:: do_Save:: call SMS_Person::mail_signup ");
	$summ .= qq{<p> at end of Summary,,,To change your info, go to 
             <a href="http://$webhost/cgi-bin/SMS/Edit?cn=$cn">
                http://$webhost/cgi-bin/SMS/Edit?confirmationnumber=$cn</a>
              </p>  };
	my $email = $part->{email};
    SMS_Person::mail_signup($email, $asum );
}

sub do_check_params{
    Debug::dsay ("do_check_params:: ");
	my $err = SMS_html_Util::check_input($q);

	if ($err) {
		print $err;
		my $html = SMS_html_Util::student_register($q, "student");

		print $html;
		print  qq{<p>$qsub</p>};
	} else {
		do_Save();
	}
}
sub do_thanks {
#   my $name = $q->param{"full_name"};
    my $summ = shift;
    my $cn = shift;
    my $out = qq{ <div class="thanks"><h1 class="SMS">SMS signup</h1>
                <p> Thanks for your interest in the student shop course. <br /> 
               The following  information has been recorded </p> $summ <br />
              <p> You should receive
               an invitation to a course via email when you are 
               scheduled <br /> To change your info, go to 
             <a href="http://$webhost/cgi-bin/SMS2/cgi/Edit?confirmationnumber=$cn">
                http://$webhost/cgi-bin/SMS2/cgi/Edit?confirmationnumber=$cn</a>
              </p></div> };
    print $out;
}

sub get_Intro {
    my $ifile = "/www/Gform/SMS/lib/signup_intro_text";
 
    my $intro = "";
    {
	open (X, $ifile) || warn "cannot open $ifile \n";
	local ( $/ );
	$intro = <X>;
	close X;  
    }
   return $intro;
}

sub dump_it
{
	print "<h2> Dump of the query </h2><br />\n";
        print $q->Dump;
        print "<hr />";
}


