#!/usr/bin/perl -w

use lib "/www/Gform/sshop/lib/";
use lib "/www/Gform/lib";
use Date::Calc qw(Delta_Days Add_Delta_Days Week_of_Year Today Monday_of_Week);
use Data::Dumper;
use sshop_part;
use Debug;

Debug::Set_Debug(1, "text");
my $week =2;

my %edata =  sshop_part::get_Data_by_ID();

 
       my $id = 15;
       my $es = $edata{$id};
       my $name = $es->{full_name};
       my $email = $es->{email};
       print " nma e {$name} email, {$email}\n";
 
  