#!/usr/bin/perl -w

use lib "../";
use lib "/www/Gform/lib";
use Date::Calc qw(Delta_Days Add_Delta_Days Week_of_Year Today Monday_of_Week);
use Data::Dumper;
use SMS_Person;
use Debug;

Debug::Set_Debug(1, "text");


 foreach my $id ( qw [ 00900700] )
 {
     my $cn = SMS_Person::confirmationnumber($id);
     my $i2 = SMS_Person::cn2sn($cn);
     print "id {$id} cm {$cn} restored id {$i2}}\n";
 }
# my $cn = sshop_part::confirmationnumber($id);
