#!/usr/bin/perl -wT

use lib "/www/Gform/sshop/lib/";
use lib "/www/Gform/lib";


use Debug;
use sshop;
use Data::Dumper;
Debug::Set_Debug(1,"ansi");

Debug::dsay("this is show invite");

my $im = sshop_part::get_InviteMessage();

    print $im;

print "\n\n that's all fols\n";

