#!/usr/bin/perl -w

use lib "..";
use lib "/www/Gform/lib";
use Date::Calc qw(Delta_Days Add_Delta_Days Week_of_Year Today Monday_of_Week);
use Data::Dumper;
use SMS_Person;
use Debug;

Debug::Set_Debug(1, "text");

my $sn = "00900700";
my $part = SMS_Person::get_app_by_ID($sn);


print Dumper($part);

foreach my $tag  (qw (UBC_id full_name confirmationnumber superEmail) )
{
    print "$tag --> $part->{$tag} \n ";

}

 
    
exit;

