#!/usr/bin/perl -w

use lib "/www/Gform/sshop/lib/";
use lib "/www/Gform/lib";
use Date::Calc qw(Delta_Days Add_Delta_Days Week_of_Year Today Monday_of_Week);
use Data::Dumper;
use sshop_part;
use Debug;

Debug::Set_Debug(1, "text");

my $id = 7;
my %element_info = my %el_info =  sshop_part::get_element_info();
my $this_app = sshop_part::get_app_by_ID($id);

    Debug::dsay ("This is main page sub ");
 
foreach my $t ( sort {$element_info{$a}{rank} <=>
                      $element_info{$b}{rank} } keys %element_info )
{
    my $value = $this_app->{$t} ? $this_app->{$t} : "" ;
    my $pout = $element_info{$t}{prompt} ? $element_info{$t}{prompt}: "";

    print " tag {$t} prompt $pout  value {$value}\n";
}
    
exit;

