#!/usr/local/bin/perl -w

use lib "/www/Gform/sshop/lib/";
use sshop_part;
use Debug;
use Data::Dumper;
use Date::Calc qw(Delta_Days Add_Delta_Days Week_of_Year Monday_of_Week );
Debug::Set_Debug(1,"ansi");

my %xweeks =  sshop_part::get_excluded_weeks();
my @Start = split "-",$xweeks{start};
my @Slast = split "-",$xweeks{last};

## get array of appls.
   my $start_wk = 42;
   my $num_wk   = 4;
my %eweeks =  sshop_part::get_excluded_weeks();
my %pweeks =  sshop_part::get_Week_Avail();
my %edata  =  sshop_part::get_Data_by_ID();
my $un_ref =  sshop_part::get_UnRestricted_Weeks($start_wk, $num_wk);



my %unrest = %$un_ref;

foreach $d ( sort keys %unrest)
{
   print "date: $d ";
   my $nunrest = scalar @{$unrest{$d}};
   print join", ", @{$unrest{$d}};
   print "\n";
#   print " $nunrest unrestricteds \n";
}
my $thisdate = "2012-10-16";

foreach my $ix ( @{$unrest{$thisdate}} )
{
   my $es = $edata{$ix};
   my $name = $es->{full_name};

   print " id $ix has norest $name\n";

}
