#!/usr/bin/perl -w


## test the update course record routine

use lib "/www/Gform/sshop/lib/";
use lib "/www/Gform/lib";
use Date::Calc qw(Delta_Days Add_Delta_Days Week_of_Year Today Monday_of_Week);
use Data::Dumper;
use sshop_part;
use Debug;
Debug::Set_Debug(1, "text");


##from Admin
my $id =3;
my $iso_wk ="2013-W23";
sshop_part::update_course_record($iso_wk, $id, "Delete");

