#!/usr/bin/perl -wT

use lib "/www/Gform/sshop/lib/";
use lib "/www/Gform/lib";

use Date::Calc qw(Week_of_Year);
use Debug;
use sshop_part;
use Data::Dumper;
Debug::Set_Debug(1,"ansi");

Debug::dsay("this is list_exweeks");

my %weeks =  sshop_part::get_excluded_weeks();

#print Dumper(%weeks);

my @start = split "-",$weeks{start};

print "arrayed start week is ", (join ",",@start),"\n";

print "start week is $weeks{start}\n";
print "last week is $weeks{last}\n";
my %eweeks = %{$weeks{"exluded"}};
foreach my $t ( sort  byISO keys %eweeks  )
{
    my @date = (split "-",$t);
    my $w = Week_of_Year(@date);
    my $value= $eweeks{$t};
   
    print "tag {$t} comment {$value} week {$w}  \n";
   
}
exit;
sub byISO
{
    my ($ay, $am, $ad);
    my ($by, $bm, $bd);
   
    if ( $a =~ /(\d\d\d\d)-(\d\d)-(\d\d)/)
    {
	$ay = $1;
        $am = $2;
        $ad = $3;
    } else
    {  	$ay = $am = $ad = 0 ;
    }
    if ( $b =~ /(\d\d\d\d)-(\d\d)-(\d\d)/)
    {
	$by = $1;
        $bm = $2;
        $bd = $3;
    } else
    {  	$by = $bm = $bd = 0 ;
    }

    $ay <=> $by ||
    $am <=> $bm ||
    $ad <=> $bd;
}




