#!/usr/bin/perl -w

use lib "/www/Gform/sshop/lib/";
use lib "/www/Gform/lib";
use Date::Calc qw(Delta_Days Add_Delta_Days Week_of_Year Today Monday_of_Week);
use Data::Dumper;
use sshop_part;
use Debug;

Debug::Set_Debug(1, "text");

## fake some data
my %names =();
my $week ="2013-W50";
my $inst  = "mighty Mouses";
foreach my $i ( 1..4)
{
    $names{$i} = "name$i"
}

  sshop_part::save_Course($week, $inst, %names);

